# Generated by Django 4.2 on 2023-04-27 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 27)),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
