# Generated by Django 4.2 on 2023-04-22 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='room_num',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 22)),
        ),
    ]
