# Generated by Django 4.2 on 2023-04-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_attendancelog_date_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='room_num',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
