# Generated by Django 4.2 on 2023-05-13 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lesson_num_alter_attendancelog_date_alter_lesson_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.SmallIntegerField(choices=[(2, 'Одобрено'), (1, 'Ожидание'), (0, 'Не одобрено')], default=1),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='date',
            field=models.DateField(default=datetime.date(2023, 5, 13)),
        ),
    ]
